# Generated by Django 5.1.4 on 2024-12-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_leads_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='phone_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
